DROP TABLE DATABASECHANGELOG;
DROP TABLE DATABASECHANGELOGLOCK;
DROP TABLE JHI_AUTHORITY;
DROP TABLE JHI_PERSISTENT_AUDIT_EVENT;
DROP TABLE JHI_PERSISTENT_AUDIT_EVT_DATA;
DROP TABLE JHI_USER;
DROP TABLE JHI_USER_AUTHORITY;
DROP TABLE OAUTH_ACCESS_TOKEN;
DROP TABLE OAUTH_APPROVALS;
DROP TABLE OAUTH_CLIENT_DETAILS;
DROP TABLE OAUTH_CLIENT_TOKEN;
DROP TABLE OAUTH_CODE;
DROP TABLE OAUTH_REFRESH_TOKEN;
DROP TABLE AVALIACAO_MODELO;
DROP TABLE PERGUNTA;
DROP TABLE EQUIPE;
DROP TABLE EQUIPE_MEMBROS;

