version: '2'
services:
    avaliacao360chiote-app:
        image: avaliacao360chiote
        external_links:
            - avaliacao360chiote-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/avaliacao360chiote
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    avaliacao360chiote-postgresql:
        extends:
            file: postgresql.yml
            service: avaliacao360chiote-postgresql
